"""structured location address

Revision ID: 4533be21567a
Revises: e7a7037fdef0
Create Date: 2026-09-19 12:18:17.841512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4533be21567a'
down_revision: Union[str, None] = 'e7a7037fdef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('municipality', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lot', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('block', sa.String(length=50), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('block')
        batch_op.drop_column('lot')
        batch_op.drop_column('street')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('municipality')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
