"""material stock and service materials applied

Revision ID: 467d5ffa67f2
Revises: 4533be21567a
Create Date: 2026-09-19 12:50:28.035419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467d5ffa67f2'
down_revision: Union[str, None] = '4533be21567a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_applied', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('materials_applied')

    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
